### ISSUE TITLE
[Feature Request] Search Bar

### ISSUE THREAD

**Issue by evlsmurf** [ashwin-pc/hiccup#1]
Adding a search bar for google/duckduckgo/etc. With option of above or below the Featured Links section if possible.

**Comment by ashwin-pc** [comment]
@evlsmurf What exactly is the use case for this? Since on all major browsers, the address bar always doubles up as a search bar.

The search in the app currently is configured to only search for existing links on the start page. I **could** overload it to also search using a search provider, but that is a lot of work and want to understand the requirement before i decide to rework that section.

**Comment by evlsmurf** [comment]
Just for searching, guess i just got use to using them from other startpages. Not necessarily needed like u said.

**Comment by ashwin-pc** [comment]
https://github.com/ashwin-pc/hiccup/pull/3

**Comment by ashwin-pc** [comment]
@evlsmurf I see why most start pages use it now. Hope you like this implementation.
