### ISSUE TITLE
Push local change to server

### ISSUE THREAD

**Issue by AdrienVIN** [ashwin-pc/hiccup#10]
Hello @ashwin-pc, 

Just to be sure, right now it's not possible to edit the .json config file locally and to push it to the server so that other clients can get the latest version?

Thanks

**Comment by ashwin-pc** [comment]
Hmm that's an interesting use case. There are two different features in your question. 

1. The ability to edit the config from the app and save it to the server. This is currently not possible and a lot tricker since this is a static start page. I'm working on alternative solutions for this but it won't be coming anytime soon.
2. The ability to push the changes to the other client automatically. This is possible, and can be achieved with some form of version control in the config. If you think this is useful without the first, I can open a separate issue and track it there :)

**Comment by AdrienVIN** [comment]
Thanks for your answer and thanks for seeing the problem in two features!

The second one makes a lot of sense but I'm not really a great judge... I actually use hiccup for my business so that all my colleagues can have the same start page but the "co-op feature" ("hey Adrien I changed a shortcut, can you see it?") is maybe very far from the original idea of this project. 

Again thank you for your answer.

**Comment by ashwin-pc** [comment]
Yeah, it's not a use case it was built to support. The biggest challenge there is security. You only want a user with the right privileges to be able to change the startpage. I eliminated this issue by making it static, so that only the user who has access to the server where the config is hosted is allowed to edit the default config. This way it's the responsibility of the server to setup the correct privileges.

That being said if your immediate worry is the ability to share these changes, it should be fairly straightforward to download the latest config once it's edited locally and share that file to the server admin or anyone with permissions to modify the default config. It's not as simple as clicking save on the page, but it's an alternative for now.

Hope this helps. Closing this issue for now since I already have an issue open for the first use case. Feel free to reopen it if you have any other questions :)

**Comment by AdrienVIN** [comment]
Thank you Ashwin for the time taken for these answers. The alternative you propose is really interesting and easy to implement so yeah I agree 100% with you.
