### ISSUE TITLE
[Feature] Lockdown/Disable Edit Mode

### ISSUE THREAD

**Issue by Unkn0wnCreator** [ashwin-pc/hiccup#11]
I currently use Flame for a public link Archive to my services,

but I think this project would be a little better for me, but users should only get the latest version of my static config. So an option to toggle it in the config would be nice.

Furthermore, it would be nice to lock it down with a password or pin code or webauthn so that I can use the Web UI to configure new links, but normal users should not change the URLs for themselves

But I don't want to say that you need to change it, maybe my use case is too small.

**Comment by ashwin-pc** [comment]
I think this is really good idea. The current is tailored for my use cases but having the latest static config is a very valid use case. Should be fairly simple to implement. I may take a stab it soon. Disabling editing as well. There are a few meta config options I've been meaning to add. Just never got to it. 

Auth however is a bigger task. I haven't had the time to think about it properly but it is also something that I want to bring in. For now though you can use `.htpasswd` to restrict your website if that meets your need. Let me open a separate issue to track auth separately. 

Not promising that I'll get to auth, but atleast I start a conversation on how to implement it there.

**Comment by ashwin-pc** [comment]
#8 is the metadata issue

**Comment by ashwin-pc** [comment]
Closing this issue since it is now possible to disable edit mode using the readonly property in the config. This also limits the user to only sync the latest config using the sync button.

As for the auth stuff, i dont think i will be implementing that because that IMO should be handled by the server and not this application. Feel free to raise a PR if you want to pick that up :)
