### ISSUE TITLE
Add cache mode to config

### ISSUE THREAD

**Issue by AdrienVIN** [ashwin-pc/hiccup#24]
Hi @ashwin-pc ! 

I'd like to disable the cookie storage and the offline version of the homepage, do you know if this could be done easily? 

Maybe to have a variable in manifest.json so we can specify if we want this feature or not? 

Thank you :)

**Comment by ashwin-pc** [comment]
I dont have an answer off the top of my head. Can you help me understand what you're trying to do here?

**Comment by AdrienVIN** [comment]
Oh sorry, for a better explanation I will state my case: 

1. I update the config.json via ftp
2. After the modification, I only have the old version "cached" on my browser.
3. I have to delete the cookie
4. After a reload, the change appears and everything is fine.

The goal is only to skip steps 2 and 3.

So yes I'm trying to invalidate the local config and fetch the global config over the network, and this driveng by a variable in the manifest.json file. 

It's seems that I have temporaly solve this by commenting thoses lines; 

```
export const load = async (
  overridingConfig?: ConfigEntity
): Promise<ConfigEntity> => {
  // Pick the overriding connfig if it exists first
  if (overridingConfig && isValid(overridingConfig)) return overridingConfig

//   // Then check the local storage if we have one saved there
//   const localConfigString = localStorage.getItem(CONFIG_KEY)
//   const localConfig = !!localConfigString && JSON.parse(localConfigString)
//   if (isValid(localConfig)) return localConfig

//   // Else fetch the default file.
//   try {
//     const remoteConfig = await sync()
//     return remoteConfig
//   } catch (e) {
//     console.error('Failed to load config from url: ', URL, e)
//     triggerConfigError(`Failed to load config from url: ${URL}\n${e}`)
//   }

//   return EMPTY_CONFIG

  const remoteConfig = await sync()
  return remoteConfig
}
```

**Comment by ashwin-pc** [comment]
Got it. Yeah that effectively turns off caching. This is definitely another feature worth adding but i'm not sure when i can get to it right now. If you're interested i can help you introduce a PR for this feature with this and a few other caching strategies. 

The approach used right now is identical to the [cache only](https://developer.chrome.com/docs/workbox/caching-strategies-overview/#cache-only) strategy for service workers. I was planning on implementing some of the other strategies that could be set using a config value.

**Comment by ashwin-pc** [comment]
Updating the issue to focus on caching strategies. The plan here would be to have at least the first 3 strategies from here: https://developer.chrome.com/docs/workbox/caching-strategies-overview/

Since this deals with the config itself, storing this value in the config would not make the most sense. Some options for storing this value are:
1. URL params (defaults to Cache first, falling back to network)
2. Config (This becomes a lil tricker but again the default will check the cache to see what this value is for the caching strategy and then act accordingly)
3. Build param. This is the least preferred since it will not be accessible to folks who do not build the project
4. Another config for setting that are for the admin only. This is also not preferred since it complicates the project unnecessarily.

I'm open to other ideas :)

**Comment by ashwin-pc** [comment]
Added with #33. To use this feature use the url param `cache` and with one of the following values
- `cache`
- `network`
- `cache-first`
- `network-first` (default)

e.g.

```
http://test.com?cache=network
```
